server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

logging:
  level:
    org.zalando.logbook: TRACE

spring:
  profiles:
    group:
      local: "local,env"
    active: local

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
    open-in-view: false

  redis:
    host: localhost
    port: 6379

  session:
    store-type: redis

  data:
    redis:
      repositories:
        enabled: false

env:
  LAPI_URL: ${LAPI_URL}