server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

logging:
  level:
    org.zalando.logbook: TRACE

spring:
  profiles:
    group:
      local: "local,env"
    active: local
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
            scope:
              - profile
              - email

  jpa:
    properties:
      hibernate:
        show_sql: false
        default_batch_fetch_size: 100
    open-in-view: false

  redis:
    host: localhost
    port: 6379

  session:
    store-type: redis

  data:
    redis:
      repositories:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8888

env:
  LAPI_URL: ${LAPI_URL}